import Head from 'next/head'
import { Footer, Header } from '../components'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>detoxify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <section className='py-16'>
        <div className='max-w-screen-lg px-5 mx-auto text-center w-full'>
          <h1 class='text-7xl font-bold'>A tool for a better experience.</h1>
        </div>
      </section>
      <Footer/>
    </div>
  )
}
