import Head from 'next/head'
import { Footer, Header } from '../components'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>detoxify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className='main'>
        <h1>Test</h1>
      </main>
      <Footer/>
    </div>
  )
}
